services:
  - type: web
    name: rich-onebox-emails-backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: ELASTICSEARCH_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
